### ISSUE TITLE
[Discussion] Best practice for adding top level metadata

### ISSUE THREAD

**Issue by idunbarh** [CISA-SBOM-Community/SBOM-Generation#17]
Discussion for Aug 13th 2024 tiger team meeting focused on who best to add top level metadata to an SBOM. For example top level license, supplier, copyright, etc ... which would not be known by an existing sbom generation tool.

The discussion revolved around using `jq` to merge a sbom from a generation tool with additional json data.

For example ...

- [bomctl.cdx.json](https://github.com/user-attachments/files/16606148/bomctl.cdx.json) - a syft generated sbom of the bomctl go binary.
- [metadata.cdx.json](https://github.com/user-attachments/files/16606149/metadata.cdx.json) - a json file containing bomctl specific metadata.

... can be merged using `jq` with the following command ...

```
jq --slurp '.[0] * .[1]' bomctl.cdx.json metadata.cdx.json > merged.jq.cdx.json
```

... to produce this sbom with correct metadata ...

- [merged.jq.cdx.json](https://github.com/user-attachments/files/16606160/merged.jq.cdx.json)

Are there better approaches to this problem?

**Comment by vpetersson** [comment]
I like this approach. My only objection is that we agreed to produce both SPDX **and** CycloneDX and we don't want to maintain *two separate* meta data files (one for CycloneDX and one for SPDX). 

Perhaps we can just alternate between the two and just have a conversion process between them.

Thoughts?

**Comment by riteshnoronha** [comment]
@idunbarh in https://github.com/interlynk-io/sbomasm which allows for spec agnostic merging, we have a feature which allows to specific top-level attributes. Although currently the tool requires a minimum of 2 sboms, we could relax that requirement and act as a spec agnostic enricher. 

The top level attributes can be provided via a config file, or via command-line which could be suitable for CI/CD.  If interested let me know i can make the changes. 

```
➜  ~ sbomasm generate
app:
  name: '[REQUIRED]'
  version: '[REQUIRED]'
  description: '[OPTIONAL]'
  author:
  - name: '[OPTIONAL]'
    email: '[OPTIONAL]'
  primary_purpose: '[REQUIRED]'
  purl: '[OPTIONAL]'
  cpe: '[OPTIONAL]'
  license:
    id: '[OPTIONAL]'
  supplier:
    name: '[OPTIONAL]'
    email: '[OPTIONAL]'
  checksum:
  - algorithm: '[OPTIONAL]'
    value: '[OPTIONAL]'
  copyright: '[OPTIONAL]'
output:
  spec: cyclonedx
  file_format: json
assemble:
  include_dependency_graph: true
  include_components: true
  flat_merge: false
  hierarchical_merge: true
  assembly_merge: false
```
